import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app_sidebar";
import { Toaster } from "@/components/ui/sonner";
import { BreadcrumbsBar } from "@/components/breadcrumbs-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <div className="w-full bg-background text-accent-foreground">
            <div className="flex gap-4 items-center">
              <SidebarTrigger />
              <BreadcrumbsBar />
            </div>
            <main className="h-full px-4 py-4">{children}</main>
          </div>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
